name: wheelchair
channels:
  - defaults
dependencies:
 
  - pip:
    - imutils==0.5.4
    - numpy==1.21.2
    - opencv-python==4.5.3.56
    - pygame==2.0.1
    - pyzbar==0.1.8
    - simple-pid==1.0.1

